#! /usr/bin/env python3
# coding: utf8
"""
Copyright (C) Harrygiel - All Rights Reserved
Unauthorized use of this file or any file from this project, via any medium is strictly prohibited

Seriously guys, you just have to ask, I want to know who will use this.

Chamot V2.1
Biere Module

Creator: MemePasMoi
"""

from __future__ import unicode_literals

import sys

sys.path.append('module')
from BotModule import BotModule
import random

class Biere(BotModule):
    """ Class: Biere Module Class"""
    def __init__(self, parent, default_module_node):
        super(Biere, self).__init__(parent, default_module_node)

    def call_handle(self):
        """ Method: executed when the module event is raised """
        if self.start_with_call_set() is False:
            return

        sender = self.argument[0]
        msg = self.argument[1]
        target = self.argument[2]

        self.biere_list = [
            "Aecht Schlenkerla Eiche Doppelbock",
            "08003 Barceloneta",
            "08015 Eixample",
            "109",
            "11 Siècles de Normandie",
            "1209",
            "1356 Jean le Bon",
            "1356 Prince Noir",
            "15th Anniversary Imperial Black IPA",
            "1664",
            "1664 Gold",
            "1664 Millésime 2011",
            "1845",
            "2 Craigs",
            "2 di Picche",
            "22 Verguenza Summer",
            "28 Brett",
            "3 Brasseurs Triple (la)",
            "3 Ermites Blonde (les)",
            "3 Loups IPA",
            "3 Ter",
            "3° Miglio",
            "5 A.M. Saint",
            "5 Barrel Pale Ale",
            "507 Clovis",
            "621",
            "7 Seas IPA",
            "732 Charles Martel",
            "8 Ball",
            "8-6 Extrême",
            "A Freewheelin' IPA",
            "A l'Unisson",
            "À la Table du Diable",
            "A.K. Damm",
            "Abbaye d'Aulnes Blonde 6",
            "Abbaye d'Aulnes Blonde 8",
            "Abbaye d'Aulnes Brune 6",
            "Abbaye d'Aulnes Brune 8",
            "Abbaye d'Aulnes Val de Sambre",
            "Abbaye de Forest Blonde",
            "Abbaye de Gembloux",
            "Abbaye de St Bon Chien",
            "Abbaye de St Landelin",
            "Abbaye de St Landelin Spéciale Noël",
            "Abbaye de Valmagne",
            "Abbaye des Rocs Brune",
            "Abbaye des Rocs Grand Cru",
            "Abbaye des Rocs Spéciale Noël",
            "Abbaye du Val Dieu Grand Cru (l')",
            "Abbaye du Val Dieu Noël (l')",
            "Abbot Ale",
            "Abdis Brune",
            "Abdis Triple",
            "Abraxxxas",
            "Abstrakt AB:08",
            "Achel Blonde",
            "Achel Brune",
            "Achel Extra Bruin",
            "Adelscott",
            "Adriaan",
            "Adriaan Rosé",
            "Adriaen Brouwer",
            "Aecht Schlenkerla Rauchbier Märzen",
            "Aecht Schlenkerla Rauchbier Weizen",
            "Aegte Fynsk Ale n°16 1/2",
            "Affligem Blonde",
            "Affligem Christmas",
            "Affligem de Noël",
            "Affligem Dubbel",
            "Affligem Tripel",
            "Affoleuse blonde (l')",
            "Agent Provocateur",
            "Agrumes of Love",
            "Aguila",
            "Aiguille Blanche (l')",
            "Akerbeltz Ambrée (Gorrosta)",
            "Akerbeltz Blanche (Xuria)",
            "Akerbeltz Blonde (Horaila)",
            "Alba Scots Pine Ale",
            "Alesmith Grand Cru",
            "Alesmith IPA",
            "Alesmith X Extra Pale Ale",
            "Alex le Rouge",
            "Alexander Black",
            "Alice Porter",
            "Aliénor Blonde",
            "All Blacks NZPA",
            "Alouette de Gascogne Ambrée",
            "Alouette de Gascogne Blanche",
            "Alouette de Gascogne Blonde",
            "Alt Sept 65",
            "AltenMünster Brauer Bier",
            "Altitude 6",
            "Alvinne Tripel",
            "Alzina Ambrée la Bufeta",
            "Alzina Blonde",
            "AM:PM",
            "Amadeus",
            "Amarillo",
            "Ambrée des Flandres",
            "America Fuck Yeah",
            "American Dream (sans gluten)",
            "Amérindienne (l')",
            "Amparo",
            "An Que Van (l')",
            "Anchor IPA",
            "Anchor Porter",
            "Anchor Small Biere",
            "Anchor Steam Biere",
            "Andechser Bergbock Hell",
            "Andechser Doppelbock Dunkel",
            "Andechser Dunkel Weissbier",
            "Andechser Spezial Hell",
            "Andechser Weissbier Hefetrüb",
            "Angélus (l')",
            "Angélus de Noël (l')",
            "Angry Boy Brown Ale",
            "Annada 1210 (l')",
            "Anosteke",
            "Anosteke Brune",
            "Antartica",
            "Antidote",
            "Antisociale",
            "Antytax Roi des Astyanax",
            "Anvil Ale ESB",
            "Aour Du",
            "Aphrodisiaque",
            "Apocalypse Now",
            "Apple White",
            "Ar-Men Ambrée",
            "Ar-men Blonde",
            "Arabier",
            "Aramis French Smash Biere",
            "Ardenne Stout",
            "Arend Blond",
            "Arend Double",
            "Arend Triple",
            "Arlésienne (l')",
            "Arrogant Bastard Ale",
            "Art Fosca Stout",
            "Art Malté Ambrée",
            "Art Malté Bière de Garde",
            "Art Malté Bière de l’Instant - Pils Fermentation",
            "Art Malté Bière de l’Instant Blonde IBU – 80 IBU",
            "Art Malté Bière de l’Instant Blonde – 10 IBU",
            "Art Malté Blonde",
            "Artevelde",
            "Artevelde Grand Cru",
            "ASM Auv'Alie",
            "Asociale (l')",
            "Astra Rotlicht",
            "Astra Urtyp",
            "Atlantic APA",
            "Atlantic au pineau",
            "Atlantic Blonde",
            "Atlas",
            "Aubeloun",
            "Augustijn",
            "Augustijn Brune",
            "Augustijn Grand Cru",
            "Aupa Tovarisch Lagavulin Edition",
            "Authentique Ambrée",
            "Authentique Blonde",
            "Authentique de Noël",
            "Authentique Triple",
            "Autonomy Lost",
            "Avec les Bons Vœux",
            "Aveille (l')",
            "Aventinus",
            "Axe Edge IPA",
            "B.A.S. Ambrée",
            "B.A.S. Blonde",
            "Bacchus",
            "Back to Basis West Coast IIPA",
            "Back to Basis West Coast IPA",
            "Balthazar",
            "Baltika 3",
            "Baltika 4",
            "Baltika 5",
            "Baltika 6",
            "Baltika 8",
            "Baltika 9",
            "Band of Brothers",
            "Barbãr",
            "Barbãr Winter Bok",
            "Barbulle",
            "Barley Wine",
            "Barney Flats Oatmeal Stout",
            "Barrel Aged Gonzo Imperial Porter",
            "Bastogne Pale Ale",
            "Bâton de Feu",
            "Baudelo Abdij",
            "Bavaria 8.6",
            "Baye",
            "Bayreuther Bio Weizen",
            "Beamish",
            "Bécasse Originale Framboise",
            "Bécasse Originale Gueuze",
            "Bécasse Originale Kriek",
            "Becks",
            "Becks Gold",
            "Beerbera",
            "Beersel Bio",
            "Beersel Blonde",
            "Beersel de Froment",
            "Beersel Lager",
            "Beezeke",
            "Belgoo Luppoo",
            "Belgoo Saisonneke",
            "Belhaven Fruit Biere",
            "Belhaven Scottish Ale",
            "Belhaven Stout",
            "Belhaven Wee Heavy",
            "Bell' de Loing Ambrée",
            "Bell' de Loing Blanche",
            "Bell' de Loing Brune",
            "Belle Abeille",
            "Belle Dalle",
            "Belle en Goguette (la)",
            "Belle en Goguette - Cascade (la)",
            "Belle en Goguette - Houblonnée à cru (la)",
            "Belle Fleur",
            "Bellegems Bruin",
            "Belmonthe (la)",
            "Belzébuth",
            "Bendorf #5 Stout à la Framboise",
            "Bendorf #7 Porter au Cacao",
            "Bengal Tiger IPA",
            "Bengali Tiger IPA",
            "Bercloise Ambrée",
            "Bercloise au Cognac",
            "Bercloise Blanche",
            "Bercloise Blonde",
            "Bercloise Spéciale",
            "Bercloise Stout",
            "Berliner Kindl",
            "Bernadette",
            "Berotte",
            "Bersalis Triple",
            "Beyond the Pale",
            "Bier Breizh Blonde",
            "Bierataise Blonde Pur Malt",
            "Bière à la Reine des Prés",
            "Bière au Karkadé",
            "Bière Breizh Ambrée",
            "Bière Breizh Blanche",
            "Bière Cidrée (la)",
            "Bière d'Automne Mosaic",
            "Bière de Beloeil (la)",
            "Bière de l'Yvette Ambrée",
            "Bière de l'Yvette Blanche",
            "Bière de l'Yvette Blonde",
            "Bière de l'Yvette Brune",
            "Bière de Miel",
            "Bière de Noël",
            "Bière de Noël Fischer",
            "Bière de Saint Jacques",
            "Bière des Naufrageurs Ambrée",
            "Bière des Naufrageurs Blonde Spéciale",
            "Bière des Scopains (la)",
            "Bière du Coing (la)",
            "Bière du Démon (la)",
            "Bière du Mont Saint Aubert",
            "Bière en Barrique (Nuit de Goguette)",
            "Bière en Barrique (Saison des Amours)",
            "Bière Noire (la)",
            "Big Boy",
            "Big Eye IPA",
            "Big Foot",
            "Big Job",
            "Big Worst",
            "Binchoise Blonde",
            "Binchoise Brune",
            "Binchoise Brune (ancienne recette)",
            "Binchoise Spéciale Noël",
            "Bio Jade (la)",
            "Bionic",
            "Biscana",
            "Bishop's Finger",
            "Bitburger Premium Pils",
            "Bitch Black",
            "Black",
            "Black Albert",
            "Black Ale India Stout",
            "Black Ball Porter",
            "Black Baron",
            "Black Belette",
            "Black Butte Porter",
            "Black Cab Stout",
            "Black Chocolate Stout",
            "Black Damnation",
            "Black Damnation II Mocha Bomb",
            "Black Damnation III Black Mes",
            "Black Damnation IV Coffee Club",
            "Black Damnation V Double Black (version du ACBF)",
            "Black Dragon I.P.A.",
            "Black Hole",
            "Black Hole Peat Whisky Edition",
            "Black Hole White Wine Edition",
            "Black in Japan",
            "Black Isle Porter",
            "Black Isle Scotch Ale",
            "Black Jack Porter",
            "Black Mamba",
            "Black Sheep Ale",
            "Black Sheep Imperial Stout",
            "Black Wych",
            "Black'n Roll",
            "Blacksmiths Ale",
            "Blanche Amb'Ré (la)",
            "Blanche d'Ardennes",
            "Blanche de Chambly",
            "Blanche de la Tour Truffée",
            "Blanche de Namur",
            "Blanche de Ré (la)",
            "Blanche des Canuts (la)",
            "Blanche des Neiges",
            "Blanche du Hainaut",
            "Blanche du Mas",
            "Blanche du Mt Blanc",
            "Blanche Hermine",
            "Blaz an Amzer n°6",
            "Blind Pig",
            "Blithering Idiot",
            "Blonde Bio du Vezelay",
            "Blonde de Neanderthal",
            "Blonde de Noël",
            "Blonde du Mas",
            "Blonde du Mt Blanc",
            "Blondine Chinook Single Hop IPA",
            "Blåbic",
            "Bob's Biere",
            "Bob's Biere Bière de Noël",
            "Bob's Biere Blanche",
            "Bob's Biere Brune",
            "Bob's Biere Extra Blonde",
            "Bob's Biere Fumée",
            "Bob's Cherry Ale",
            "Bobby's Own Ginger Biere",
            "Bobeline Black Label",
            "Bock Damm",
            "Bodingtons Draught Bitter",
            "Boerinneken",
            "Bohemia Pilsen",
            "Bombardier Premium Bitter",
            "Bommen & Granaten",
            "Bon Secours Ambrée",
            "Bon Secours Blonde",
            "Bon Secours Brune",
            "Bon Secours Myrtille",
            "Bonaventure IPA (la)",
            "Bonnet Rouge",
            "Boogoop",
            "Boont Amber Ale",
            "Bordelais Bière de Noël",
            "Boris Goudenov",
            "Bornem Double",
            "Bornem Triple",
            "Bosh Doppelbock",
            "Boskeun",
            "Bosko",
            "Bougnat Blanche à la pomme",
            "Bougnat Blonde à la Gentiane (le)",
            "Bougnat Blonde de Garde (le)",
            "Bougnat Triple (le)",
            "Bourbon",
            "Bourganel B'10",
            "Bourgogne des Flandres",
            "Bracia",
            "Brahma Chopp",
            "Brakspear Bitter",
            "Bramble Blue Ale",
            "Bran",
            "Brass Band Ambrée",
            "Brass Band Blanche",
            "Brass Band Blond",
            "Brasserie Corrézienne Ambrée",
            "Brasserie Corrézienne Blanche",
            "Brasserie Corrézienne Blonde",
            "Brasserie Corrézienne Noire",
            "Brasserie Corrézienne Rouge",
            "Brasserie Corrézienne Saison",
            "Brasserie Corrézienne Triple",
            "Brasserie de la Lanterne Blonde",
            "Brasserie des Rocs Triple Impériale",
            "Braven Apostel",
            "Brewery Ambrée (le)",
            "Breznak Original Böhmish Pils",
            "Brigand",
            "Brigand I.P.A.",
            "Brigantine Ambrée",
            "Brin de Folie",
            "Britt Blanche",
            "Britt Blonde",
            "Britt Rousse",
            "Brixton Porter",
            "Broken Dreams",
            "Brooklyn Lager",
            "Brouette (la)",
            "Brougham Ale",
            "Bruegel",
            "Brugs",
            "Brugse Tripel",
            "Brugse Zot",
            "Brun Pourfendeur (le)",
            "Brunehaut Terroir",
            "Brunehaut Tradition",
            "Brunehaut Village",
            "Bruno Pale Ale",
            "Brusseleir Zwët IPA",
            "Brut'Ale - la P'tite Bière 2010",
            "Bul",
            "Bulle des Vignes",
            "Bush Ambrée",
            "Bush Ambrée Triple",
            "Bush Blonde",
            "Bush Blonde Triple",
            "Bush de Noël Premium",
            "Bush de Noël Spécial Noël",
            "Bush de Nuits",
            "Bush Prestige",
            "Bushwacker",
            "Buteuse (la)",
            "CàB 5",
            "Cabéo'Lune",
            "Cagole",
            "Cagole Blanche à l'Ancienne",
            "Calabrune (la)",
            "Cali-België IPA",
            "Calista IPA",
            "Calypso",
            "Camber Noire",
            "Cambierra",
            "Cambrivinus Brune",
            "Camden Hells Lager",
            "Camden Pale Ale",
            "Canicule (la)",
            "Cantillon Faro",
            "Cantillon Gueuze",
            "Cantillon Kriek",
            "Cap d'Ona Blonde Rossa",
            "Cap d'Ona Spéciale au Banyuls",
            "Caracole (la)",
            "Carib Lager",
            "Carling",
            "Carlsberg Biere",
            "Casablanca Biere",
            "Cascade Pale Ale",
            "Caselle du Diable (la)",
            "Castagne",
            "Castigamatt",
            "Caulfield",
            "Caulfield Mocha Flush",
            "Caulfield Not Just Plain Vanilla",
            "Caulier Triple",
            "Caussenarde Ambrée",
            "Caussenarde Blonde",
            "Caves",
            "Celebrator",
            "Celtika",
            "Celtika blonde",
            "Centennial IPA",
            "Cervesa del Montseny Blat",
            "Cervesa Del Montseny HivernAle",
            "Cervesa del Montseny Lupulus",
            "Cervesa del Montseny Malta",
            "Cervesa del Montseny Negra",
            "Cervesia",
            "Cervoise des Ducs (la)",
            "Cervoise des Eduennes",
            "Cervoise Lancelot",
            "Ch'L'Agache",
            "Ch'ti Ambrée",
            "Ch'ti Blanche",
            "Ch'ti Blonde",
            "Ch'ti Blonde de Noël",
            "Ch'ti Triple",
            "Chaleureuse (la)",
            "Challenger Single Hop IPA",
            "Chaman",
            "Chambly Noire",
            "Chang Biere",
            "Chante-Saveurs",
            "Chaos Theory",
            "Chapeau Faro",
            "Chapitre 13",
            "Charbon",
            "Charbonnière",
            "Charles Quint Blonde Dorée",
            "Charles Quint Rouge Rubis",
            "Charliendine (la)",
            "Château Rouge",
            "Cherries from Space",
            "Cheshire Chocolat Porter",
            "Chimay Cinq Cents",
            "Chimay Dorée",
            "Chimay Grande Réserve",
            "Chimay Première",
            "Chimère de Cendre (la)",
            "Chinco (la)",
            "Chocarrubica",
            "Choco-Biscuit (la)",
            "Chocolate Stout",
            "Cholera",
            "Chopes du Moulin Ambrée au Miel",
            "Chopes du Moulin Ambrée au Thé",
            "Chopes du Moulin Blonde",
            "Chouffe (la)",
            "Chouffe IPA Houblon",
            "Chouffe N'Ice",
            "Choulette Ambrée",
            "Choulette Ambrée de Noël",
            "Choulette Blonde",
            "Chourmette (la)",
            "Christmas Ale",
            "Christmas Pale Ale",
            "Cimoise",
            "Ciney Blonde",
            "Ciney Brune",
            "Circlemaster",
            "Citra Pâle Ale",
            "Citra Weisse",
            "Citrueille Céleste de Citracado (la)",
            "Clandestine (la)",
            "Claudine",
            "Clerics Cure",
            "Coalition Old Ale",
            "Cocoa Oatmeal Stout",
            "Cognac Barrel",
            "Colomba",
            "Colorado Red",
            "Columbus",
            "Commun'Ale",
            "Confusion",
            "Conquerant",
            "Conqueror Black IPA",
            "Consecration",
            "Contes de Trancheneige",
            "ControversiAle",
            "Coopers Best Extra Stout",
            "Coopers Original Pale Ale",
            "Coopers Sparkling Ale",
            "Coq (le)",
            "Coq Orbiculaire (le)",
            "Cordiale (la)",
            "Coreff Ambrée",
            "Coreff Blanche",
            "Coreff Blonde",
            "Coreff Brune",
            "Corne de Brume",
            "Corne du Diable",
            "Corona Extra",
            "Corps Mort",
            "Corsendonk Agnus",
            "Corsendonk Christmas Ale",
            "Corsendonk Pater",
            "Corsendonk Rousse",
            "Couille de Loup",
            "Cowboy & Indien Pale Ale",
            "Craponette Bio",
            "Crate Stout",
            "Cré Tonnerre",
            "Crécelle au Miel (la)",
            "Crécelle aux Noix (la)",
            "Crécelle Bière Ambrée (la)",
            "Crécelle Bière au Chanvre",
            "Crécelle Bière Blanche (la)",
            "Crécelle Bière Rouge",
            "Crécelle Brune",
            "Crème Brûlée Stout",
            "Crespelette",
            "Crew Pale Ale",
            "Croix des Grèves Blonde (la)",
            "Croix Roussienne Ambrée (la)",
            "Croix Roussienne Blanche (la)",
            "Croix Roussienne Blonde (la)",
            "Croix Roussienne Noire (la)",
            "Croix Roussienne Rousse (la)",
            "Croix Roussienne Saison (la)",
            "Cuivrée (la)",
            "Cumberland Ale",
            "Curmudgeon Old Ale",
            "Cutthroat Porter",
            "Cuvée Angélique",
            "Cuvée d'Oscar",
            "Cuvée de Ranke",
            "Cuvée Delphine",
            "Cuvée des Trolls",
            "Cuvée Michel",
            "Cuvée René Kriek",
            "Cuvée Saint Gilloise",
            "Cuvée Spéciale Cuvée des Trolls",
            "D'Artagnan (la)",
            "d'Uvabeer",
            "Daleside Bitter",
            "Dalva",
            "Dalva Oak Aged",
            "Dame Blanche (la)",
            "Damruz",
            "Dark Force",
            "Dark Island",
            "Dark Sister",
            "Dark-O",
            "Darwin Biere",
            "Darwin's Origin",
            "das Echte Märzen",
            "das Helle",
            "das Schwarze",
            "Daughter of Autumn",
            "Dauphine Brune",
            "Dauphine Dorée",
            "DayTime Ale",
            "De Eycken Balthazar",
            "De Koninck",
            "De Koninck Blonde",
            "De Koninck Gueuze",
            "De Koninck Triple",
            "De Maeght van Gottem",
            "De Ranke Kriek",
            "Dead Guy Ale",
            "Débauche Ambrée",
            "Débauche Black Ale",
            "Débauche Blonde",
            "Débauche Saison (la)",
            "Débauche Spéciale",
            "Decadence Stout",
            "Déferlante (la)",
            "Déjantée Amber Ale",
            "Délinquante (la)",
            "Delirium Christmas",
            "Delirium Nocturnum",
            "Delirium Tremens",
            "Delta",
            "Demoiselle",
            "Demoiselle (la)",
            "Den Grooten Tocht",
            "Dernière Tentation (la)",
            "Dernière volonté",
            "Desperados",
            "Deus Brut des Flandres",
            "Devassa Tropical Ale",
            "Devassa Tropical Lager",
            "Devotion with brett",
            "Diable Rouge",
            "Diebels Alt",
            "Dinkel Acker Märzen",
            "Dinkel Acker Privat",
            "Distordue Noire (la)",
            "Divine",
            "Divine Saint Landelin (la)",
            "Doesjel",
            "Dogfish Head 120 minutes IPA",
            "Dogfish Head 60 minutes IPA",
            "Dogfish Head 90 minutes IPA",
            "Doggie Style Classic Pale Ale",
            "Dogma",
            "Dogma Original",
            "Dolmen",
            "Dominus Vobiscum Lupulus",
            "Don de Dieu",
            "Dordogne Valley",
            "Dormeuse de Khadée (la)",
            "Double Century Celebration Ale",
            "Double Sec",
            "Double Simcoe IPA",
            "Double Stout Black Ale",
            "Double Trouble",
            "Douglas Celtic Brown",
            "Dr. Jekyll",
            "Dremmwel Blonde",
            "Dremmwel Blonde Bio",
            "Dremmwel Dorée",
            "Dremmwel Rousse",
            "Drie Fonteinen Faro",
            "Drie Fonteinen Gueuze",
            "Drie Fonteinen Lambic",
            "Drie Fonteinen Oud Kriek",
            "Dry Hop Thriller",
            "Dubbel",
            "Duc d'Havré Cuvée Prestige",
            "Duc de Carnoët",
            "Ducale",
            "Duchesse Anne",
            "Duchesse de Bourgogne",
            "Duchesse de Lorraine",
            "Duckstein Original",
            "Duivels Bier",
            "Dulle Griet",
            "Dulle Teve",
            "Dunedu (la)",
            "Duvel",
            "Duvel Tripel Hop 2014 Mosaic",
            "Duvel Triple Hop",
            "Duvel Verte",
            "Earthmonk (Aardmonnik)",
            "East India Pale Ale",
            "Easy IPA",
            "Eau Bénite",
            "Ebulum",
            "Ecume de Ré (l')",
            "Edenn Breizh",
            "Efes Pilsener",
            "Effinguud",
            "Egyptienne (l')",
            "Eisenbahn Pilsen",
            "Eku 28",
            "Eku Pils",
            "Electric India",
            "Electric IPA",
            "Elixir Céleste",
            "Elliot Brew",
            "Emelisse Barley Wine",
            "Emelisse Blond",
            "Emelisse Espresso Stout",
            "Emelisse Imperial Russian Stout",
            "Emelisse Rauchbier",
            "Emelisse Triple IPA",
            "Empereur Ambrata",
            "Ename blonde",
            "Ename Dubbel",
            "Ename Tripel",
            "Enghien de Noël",
            "Entre 2 (l')",
            "Epi-Corsé (l')",
            "Equilibrista",
            "Equinox",
            "Erdinger Weissbier (Hefe)",
            "Ernestine",
            "ESB Champion Ale",
            "Estate Brewers Harvest Ale",
            "Estrella Damm Inedit",
            "Etoile d'(a)Mer",
            "Etoile du Nord",
            "Ettaler Curator Dunkler Doppelbock",
            "Euskadiko Pale Ale (EPA)",
            "Eveil des Sylphes (l’)",
            "Everards Original",
            "Exil Fiscalov",
            "Experience",
            "Explorer",
            "Export India Porter",
            "Export Stout London 1890",
            "Extase",
            "Extra IPA Restyled",
            "Extra Re Ale",
            "Fantôme de Noël",
            "Fanø Julebryg",
            "Fanø Veskyst",
            "Farmer's Harvest",
            "Faro Pertotale",
            "Fée Bistande (la)",
            "Félibrée",
            "Fiddlers Elbow",
            "Fille de l'Orge Ambrée",
            "Fille de l'Orge Blanche",
            "Fille de l'Orge Blonde",
            "Fille de l'Orge Blonde au Chanvre",
            "Fille de l'Orge Brune",
            "Fils à Papa",
            "Fin du Monde (la)",
            "Fischer de Printemps",
            "Fischer Réserve Ambrée",
            "Fischer Tradition",
            "Fischer Tradition de la Réunion",
            "Five Points IPA",
            "Fleur de Noël (la)",
            "Fleurac Blonde",
            "Fleurac de Noël",
            "Fleurac Imperial Stout au Café",
            "Fleurac Noire à la Réglisse",
            "Fleurac Rouge à la Gentiane",
            "Fleurac Triple",
            "Fleurac Triple Brune IPA",
            "FLIPA",
            "Floreal",
            "Floreffe Prima Melior",
            "Floreffe Triple",
            "Floris Cerise",
            "Floris Fraise",
            "Floris Wit",
            "Flying Shuttle",
            "Folie Douce",
            "Fort APA",
            "Fort Boyard Ambrée",
            "Fort Boyard Blanche",
            "Fort Boyard Blonde",
            "Fort Boyard Brune",
            "Fort Christmas Blond",
            "Fort Indian Pale Ale",
            "Fort Oatmeal Porter",
            "Foster's",
            "Fou'Foune",
            "Foudroyante Gueuze",
            "Foudroyante Pomme",
            "Founders Dry Hopped Pale Ale",
            "Founders Porter",
            "Four in Hand IPA",
            "Franche Profonde (la)",
            "Franziskaner Hefe-Weissbier Dunkel",
            "Franziskaner Hefe-Weissbier Hell",
            "Franziskaner Weissbier Kristallklar",
            "Fraoch",
            "Frappadingue (la)",
            "Frappiste 2010",
            "Fruit Défendu (le)",
            "Fuller's India Pale Ale",
            "Fullers Vintage Ale 2011",
            "Fumette (la)",
            "Funky Gold Amarillo",
            "Fursty Ferret",
            "Fyne Ales Hurricane Jack",
            "Fyr & Flamme IPA",
            "Gaillarde Blonde",
            "Gaillarde Brune",
            "Gaillarde Triple",
            "Galaxy Single Hop IPA",
            "Gambière de Noël (la)",
            "Game Over",
            "Gamma Ray APA",
            "Gandavum Dry Hopping",
            "Garipotte - bière de printemps 2007",
            "Gasconha Ambrée",
            "Gasconha Blanche",
            "Gasconha Blonde",
            "Gasconha Brune",
            "Gaspar",
            "Gâtine Brune (la)",
            "Gauloise Ambré (la)",
            "Gauloise Blonde (la)",
            "Gavroche",
            "Géante (la)",
            "Gens de la Lune",
            "Genziana",
            "George Killian's",
            "Georges Blanche (saison été 2007)",
            "Georges Dorée",
            "Georges Pils",
            "Georges Rousse",
            "Gift of the Magi",
            "Gilbert's Bière de Noël",
            "Gildenbier",
            "Girardin Framboise",
            "Girardin Kriek Blanche",
            "Girardin Oude Gueuze",
            "Girasole 2 (la)",
            "Gitane (la)",
            "Godefroy",
            "Gold Ochsen WeihnachtsBier",
            "Gold Qualidad",
            "Golden Champion",
            "Golden Tricky",
            "Goldeneye Pale Ale",
            "Goliath Christmas",
            "Goliath Triple",
            "Gonzo Imperial Porter",
            "Goose Island India Pale Ale",
            "Gordon Finest Red",
            "Gordon Finest Scotch",
            "Gordon Finest Silver",
            "Gordon Xmas",
            "Goudale",
            "Goudale Grand Cru",
            "Gouden Carolus Ambrio",
            "Gouden Carolus Christmas",
            "Gouden Carolus Classic",
            "Gouden Carolus Cuvée Spéciale 1958",
            "Gouden Carolus Easter",
            "Gouden Carolus Hopsinjoor",
            "Gouden Carolus Triple",
            "Gouden Carolus Van de Keizer ruban bleu",
            "Gouden Carolus Van de Keizer ruban rouge",
            "Goule (la)",
            "Goule au Bois Bandé (la)",
            "Goule Bio (la)",
            "Goule Black Prince (la)",
            "Goule Blanche (la)",
            "Goule Cognac FIBD 2012",
            "Goule Kick",
            "Goule Notre Dame (la)",
            "Goule Or (la)",
            "Goutte d'Or Charbonnière",
            "Gradisca",
            "Grain d'Orge Cuvée 1898",
            "Grain d'Orge Tradition 8",
            "Grains de Folie - Raisin Miel",
            "Grand Cru",
            "Grand Cru Bruocsella",
            "Grand Prestige",
            "Grande Chantourne",
            "Grande Marée (la)",
            "Greene King IPA",
            "Gregorius Trapistenbier",
            "Grévine (la)",
            "Grihète n°7 Cuvée d'Exception",
            "Grimbergen Blonde",
            "Grimbergen Cuvée Ambrée",
            "Grimbergen Cuvée Blanche",
            "Grimbergen Cuvée de l'Ermitage",
            "Grimbergen Dorée",
            "Grimbergen Double",
            "Grimbergen la Réserve",
            "Grimbergen Optimo Bruno",
            "Grimbergen Triple",
            "Grisette Blanche",
            "Grodziskie",
            "Grognarde (la)",
            "Grooving Hop",
            "Grosse Bertha",
            "Grottenbier",
            "Grozet",
            "Gruette",
            "Grüss de Gott Alois",
            "Gueule Noire",
            "Gueuze de Nivelles",
            "Gueuze Tilquin",
            "Guineu Antius",
            "Guineu Coaner",
            "Guineu Montserrat",
            "Guineu Riner",
            "Guineu Sitges",
            "Guinness Draught",
            "Guinness Extra Stout",
            "Guinness Foreign Extra",
            "Guinness Special Export",
            "Gulden Draak",
            "Guldenberg",
            "Gwened",
            "Gwiniz Du (Cuvée crêperie)",
            "Gypsy Rose",
            "Haacht blanche",
            "Hackney Hopster Pacific Pale",
            "Hanse-Porter",
            "Hanssens Oude Gueuze",
            "Hanssens Oude Kriek",
            "Hapchot Blonde",
            "Happy Hoppy Vicking",
            "Hardcore IPA",
            "Harvest Sun",
            "Havgus Session IPA",
            "HBC Single Hop IPA",
            "Heelch O'Hops",
            "Heen & Weer",
            "Heimdall",
            "Heineken",
            "Heineken Oud Bruin",
            "Hel & Verdoemenis",
            "Hel & Verdoemenis 666",
            "Hellekapelle",
            "Helleketelbier",
            "Hello My Name is Vladimir",
            "Hemel & Aarde",
            "Hen's Tooth",
            "Hercule Stout",
            "Herren Pils",
            "Hertog Jan Karakter",
            "Hertog Jan Natuurzuiver",
            "Hertog Jan Primator",
            "Hertog Jan Weizener",
            "Hesjeøl",
            "Hibernator Oatmeal Stout",
            "Highhops 6",
            "Highway to Ale - 666km IPA",
            "Hildegarde",
            "Hinano",
            "Hini Du",
            "Hitachino Nest XH",
            "Hivern'Ale",
            "Hivern'Ale 2011",
            "Hivern'Ale 2012",
            "Hobgoblin",
            "Hoegaarden",
            "Hoegaarden Citron",
            "Hoegaarden Grand Cru",
            "Hoegaarden Rosée",
            "Hoegaarden Spéciale",
            "Hoegarden Rosée",
            "Holsten",
            "Holy Cowbell",
            "Hombre",
            "Home",
            "Hommelbier",
            "Hond.erd",
            "Honey Dew (organic ...)",
            "Hop Harvest 2011",
            "Hop Hop Hop",
            "Hop Session",
            "Hop Trilogy Centennial",
            "Hop Trilogy Colombus",
            "Hop Trilogy Simcoe",
            "Hop Verdomme IPA",
            "Hop Weiss",
            "Hop Yard IPA",
            "Hop'sss Marie-Magdeleine",
            "Hopfenfänger Rotbier",
            "HopHopHop Amarillo",
            "HopHopHop Aramis",
            "HopHopHop Cascade",
            "HopHopHop Citra",
            "HopHopHop Equinox",
            "HopHopHop Mosaic",
            "HopHopHop Nelson Sauvin",
            "HopHopHop Pacific Gem",
            "HopHopHop Simcoe",
            "HopHopHop Triskel",
            "Hoppin' Frog BORIS The Crusher",
            "Hoppin' Frog Mean Manalishi",
            "Hoppy Cat",
            "Hoppy Christmas",
            "Hops Kill ?",
            "Hopus",
            "Horn Dog Barley Wine",
            "Hornbeer Imperial IPA",
            "I Beat yoU",
            "I Hardcore You",
            "I Wish IPA Gluten Free",
            "I.P.A Black Edition",
            "Ichtegem's Oud Bruin",
            "Ichtegem's Oud Bruin Grand Cru",
            "IFBM Bière de Noël",
            "Ikea Öl Ljul Lager",
            "Ikea Öl Mörk Lager",
            "Il Etait Lune Fois - Cascade",
            "Il Etait Lune Fois - Nelson Sauvin",
            "Imperial Black",
            "Imperial Brown Stout",
            "Imperial India Pale Ale",
            "Imperial Skärgaards Porter Cabernet Barrel",
            "Imperial Stout",
            "Imperial Stout Limited Edition",
            "India Pale Ale Centennial/Simcoe",
            "India Pale Ale Citra",
            "India Pale Ale Citra Cascade",
            "India Pale Ale Columbus",
            "India Pale Ale Mosaic Zeus",
            "India Pale Ale Simcoe/Magnum",
            "India Pale Ale Stella",
            "India Pale Ale Summit",
            "India Pale Ale Topaz",
            "Indian",
            "Índica",
            "Indica IPA",
            "Indigo IPA",
            "Innis and Gunn Oak Aged Original",
            "Inquiète (une)",
            "IPA au Paradis des Gorets",
            "IPA Centennial et Amarillo",
            "IPA Citra Galactique",
            "IPA sous Sénart",
            "IPArisis",
            "Iris",
            "Italia",
            "IV Saison",
            "Jack Hammer",
            "Jacobins Framboise Max",
            "Jacobins Gueuze",
            "Jaipur IPA",
            "Jambe de Bois",
            "Jan de Lichte",
            "Janis Porter",
            "Japan Pale Ale",
            "Je Brûle de Désir",
            "Jenlain Ambrée",
            "Jenlain Blonde",
            "Jenlain de Noël",
            "Jenlain de Printemps",
            "Jenlain Six",
            "Jever",
            "Jingo",
            "John Smith's Original Bitter",
            "Joli Rouge American Pale Ale",
            "Joli Rouge Brune d'Hiver",
            "Joli Rouge IPA",
            "Joli Rouge Milk Stout",
            "Joli Rouge Pils",
            "Jopen Bockbier",
            "Jopen Extra Stout",
            "Jopen Hoppenbier",
            "Jopen Lentebier",
            "Jopen Winterbok",
            "Juanita",
            "Julien Ambrée",
            "Julien Bière de Printemps",
            "Julien Blanche",
            "Julien Blonde",
            "Julien Blonde Forte",
            "Julien Brune",
            "Julien Indian Pale Ale",
            "Julius",
            "Kabert",
            "Kaiser Weizen Schwarzes Hefe",
            "Kameleon Triple",
            "Kanterbraü",
            "Kaou'ët Blonde Cuivrée",
            "Kaou'ët Triple",
            "Kapittel Watou Blond",
            "Kapittel Watou Prior",
            "Kapittel Watou Tripel",
            "Karland Ambrée",
            "Karland Fumée",
            "Karlsbräu",
            "Kasteel Bier Brune",
            "Kasteel Hoppy Blond",
            "Keller-bier 1402",
            "Kelpie Seawed Ale",
            "Kerasus",
            "Kerst Pater Christmas",
            "Kerzu",
            "Kilkenny",
            "Kipling",
            "Klintz (la)",
            "Kloeke Blond",
            "Kronenbourg",
            "Kult!",
            "Kwak",
            "König Pilsener",
            "Köstritzer Schwarzbier",
            "L & L Alphand Ambrée",
            "L & L Alphand Blanche",
            "L & L Alphand Blonde",
            "Lagaille Rouquinette",
            "Lager - Finesse et Caractère",
            "Lagunitas Imperial Stout",
            "Lagunitas IPA",
            "Lambicus Blanche",
            "Lancaster Bomber",
            "Lancelot",
            "Lao Bia",
            "Larme Blanche (la)",
            "Lathière Blonde du Bois des Eschelles",
            "Laubicherie Ambrée",
            "Laubicherie Ambrée à la Noix",
            "Laubicherie Blonde",
            "Laubicherie Blonde à la truffe",
            "Leffe 9",
            "Leffe Blonde",
            "Leffe Brune",
            "Leffe Kerstbier",
            "Leffe Radieuse",
            "Leffe Royale",
            "Leffe Ruby",
            "Leffe Triple",
            "Leffe Vieille Cuvée",
            "Léman Blanche",
            "Leo",
            "Leonardo Ambrée",
            "Leroy Christmas",
            "Leute Bokbier",
            "Levalloise",
            "Levitation Stone",
            "Levrette",
            "Levrette Bio",
            "Leya Bière de Noël",
            "Libertane",
            "Libertane Ambrée",
            "Libertane Blonde",
            "Libertane Brune",
            "Libertine (la)",
            "Liberty Ale",
            "Lichtervelds Blond",
            "Liefmans Cuvée Brut",
            "Liefmans Frambozen",
            "Liefmans Glühkriek",
            "Liefmans Goudenband",
            "Liefmans Jan Van Gent",
            "Liefmans Oud Bruin",
            "Life and Lamb",
            "Ligne 3",
            "Lili's Biere",
            "Lily Blue",
            "Lindemans Faro",
            "Lindemans Kriek",
            "Lindy Hop",
            "Little Sumpin' Sumpin' Ale",
            "Loburg",
            "Loch Dukoss",
            "Loirette Ambrée",
            "London Porter",
            "London Pride",
            "London Smoked Porter",
            "Lorraine",
            "Loup Blanc du Causse (le)",
            "Louwaege's Pils",
            "Lun'ion-Jacques",
            "Luna'cious",
            "Lunatique",
            "Lune et l'Autre",
            "Lune Noire",
            "Lunik",
            "Lutina Ambrio",
            "Lutina Violetta",
            "Lutine Ambrée (la)",
            "Lutine Blonde (la)",
            "Mac Queen's Nessie",
            "Mad Bitter",
            "Mad Max (la)",
            "Mad Saison",
            "Mad Tom",
            "Mad Umami",
            "Madelon (la)",
            "Madness IPA",
            "Maes",
            "Magic 8 Ball",
            "Maisel's Weisse Hell",
            "Maisel's Weisse Kristall",
            "Maisel's Weisse Original",
            "Malheur 10",
            "Malheur 12",
            "Malheur 6",
            "Malheur Brut",
            "Malheur Cuvée Royale",
            "Malheur Dark Brut",
            "Maline (la)",
            "Mallozh Ruz",
            "Malteser Weissbier (Kristall)",
            "Mamm Douar",
            "Mamouche",
            "Mandarina Dark Ale",
            "Mandragore",
            "Mandragore (la)",
            "Mandubienne Ambrée",
            "Mandubienne Blonde",
            "Mandubienne Brune",
            "Mange-Soif Blanche de Soif",
            "Mange-Soif Blonde de Soif",
            "Maniague",
            "Manneken Pis Witbier",
            "Mano Negra",
            "Maredsous Blonde",
            "Maredsous Brune",
            "Maredsous Triple",
            "Mariana Trench",
            "Marie Noëlle",
            "Martins IPA",
            "Maryline",
            "Mascaret Ambrée",
            "Mashtag 2014 Democratic Imperial Red Ale",
            "Master Brew",
            "Mastoc",
            "Maudite",
            "Maverick",
            "Maximator",
            "Maximus",
            "Mc Ewan's Scotch",
            "McMummy",
            "Meantime Chocolate",
            "Meantime Coffee Porter",
            "Meantime London Stout",
            "Meantime Pilsner",
            "Meantime Raspberry",
            "Meantime Wheat",
            "Meister Pils",
            "Melchior",
            "Melig",
            "Mellifica Cervoise",
            "Melmor",
            "Mélusine",
            "Menestho",
            "Merchien Bronze - IPA",
            "Merchien Dorée - Bitter",
            "Mère Noël (la)",
            "Messon (la)",
            "Meteor de Noël",
            "Meteor Pils à la fleur de Houblon",
            "Methusalem",
            "Meule (la)",
            "Meunière Brune (la)",
            "Midòna",
            "Mikkel & Menno",
            "Mikkeller Hop Series Amarillo",
            "Mikkeller Hop Series Cascade",
            "Mikkeller Hop Series Centennial",
            "Mikkeller Hop Series Colombus",
            "Mikkeller Hop Series Simcoe",
            "Milk Stout",
            "Miss Sour",
            "Mission Chinese Food",
            "Mission Pale Ale",
            "Mister Hyde",
            "Mistinguett",
            "Modus Operandi",
            "Moinette Biologique",
            "Moinette Blonde",
            "Moinette Brune",
            "Moneuse (la)",
            "Monk",
            "Monk's Elixir",
            "Monk's Stout",
            "Montagnarde (la)",
            "Montreuilloise IPA Mandarina Bavaria",
            "Monts des Cats",
            "Monty Python Holy Grail",
            "Mooi & Meedogenloos",
            "Moor Somerland Gold",
            "Moor Top",
            "Moose Blues",
            "Mor Bihan",
            "Mor Braz Ambrée",
            "Morgane",
            "Morpheus Dark",
            "Morpheus Wild",
            "Morsure (la)",
            "Mort Subite Blanche",
            "Mort Subite Gueuze",
            "Mort Subite Kriek",
            "Moska Negra",
            "Moska Rossa",
            "Mosser (la)",
            "Motuecha",
            "Motueka Single Hop IPA",
            "Moulins d'Ascq Ambrée",
            "Mouska",
            "Mousse Ambrée (la)",
            "Mousse Blonde (la)",
            "Mousse Dorée (la)",
            "MPC",
            "Mum's the Word",
            "Murmansk",
            "Murphy's Irish Stout",
            "My Antonia",
            "Myrha",
            "Mysteria",
            "Mythique Saint Landelin",
            "Nanny State",
            "Negra Modelo",
            "Neudorf Red Ale",
            "Nevermore",
            "Newcastle Brown Ale",
            "Newton",
            "Nice to Meet You",
            "Niks Meer Nodig",
            "Ninkasi Ambrée",
            "Ninkasi Blanche",
            "Ninkasi Blonde (bouteille)",
            "Ninkasi I.P.A.",
            "Ninkasi Noire",
            "Ninkasi Rousse",
            "Ninkasi Saison - Agrippine",
            "Ninkasi Triple",
            "Niwi Ninøn",
            "Noblesse",
            "Noël - Christmas - Weihnachts",
            "Noir de Dottignies",
            "Noiraude",
            "Nora",
            "Nordika",
            "Norlands Guld Export",
            "Norman Gold",
            "Northmaen Ambrée",
            "Northmaen Bière au Miel",
            "Northmaen Blanche",
            "Northmaen Brune",
            "Norwegian Wood",
            "Nos Régions Ont du Talent Blonde",
            "Nostradamus",
            "Nounette",
            "Nova Schin",
            "Nuit de Goguette 3.9%",
            "Nuit de Goguette 7%",
            "Nuit de Goguette Double Stout à l'Avoine",
            "Nuit de Goguette Weizenbock",
            "Nuits Blanches",
            "Nøgne Ø #100",
            "Nøgne Ø #500",
            "Nøgne Ø Blond",
            "Nøgne Ø Brun",
            "Nøgne Ø Imperial Brown Ale",
            "Nøgne Ø Imperial Stout",
            "Nøgne Ø India Saison",
            "Nøgne Ø IPA",
            "Nøgne Ø Mandarina IPA",
            "Nøgne Ø Porter",
            "Nøgne Ø Saison",
            "O'Haras Irish Pale Ale",
            "O'Haras Irish Red",
            "O'Haras Irish Stout",
            "O1",
            "Oak Aged Dubbel",
            "Oaked Arrogant Bastard Ale",
            "Occita (l')",
            "Odo",
            "Oerbier Special Reserva",
            "Oettinger Dunkles Hefeweizen",
            "Oettinger Export",
            "Old Foghorn",
            "Old Freddy Walker",
            "Old Gold",
            "Old Guardian",
            "Old Heather",
            "Old Henry",
            "Old Numbskull",
            "Old Peculier the Legend",
            "Old Scratch Amber Lager",
            "Old Speckled Hen",
            "Old Stoat",
            "Old Tom Original",
            "Old Viscosity Ale",
            "Oldarki au Patxaran",
            "Olmaia la 9 (l')",
            "Olta Ambrée",
            "Olta Blanche",
            "Olta Blonde",
            "Omega",
            "Ommegang Abbey Ale",
            "Ondine d'Oray",
            "One Claw",
            "Open & Bloot",
            "Opération Houblon Durci",
            "Oppale",
            "Ordinary Bitter",
            "Original Leipziger Gose",
            "Orson Ale",
            "Orval",
            "Ottweiler Pils",
            "Oud Beersel Kriek",
            "Oud Beersel Lambic",
            "Oudbeitje",
            "Oude (Gueuze Tilquin)²",
            "Oude Geuze Boon",
            "Oude Geuze Vieille",
            "Oude Quetsche Tilquin",
            "Ourse Blonde",
            "Ourse Miel",
            "Overall IIPA",
            "Overdose",
            "Oxford Gold",
            "Oxit Brune à la Châtaigne",
            "Oyster Stout",
            "P'tit Klintz (le)",
            "P'tite Frap'",
            "P'tite Mère (la)",
            "P'tite Sylvie (la)",
            "P2",
            "Pacific Dark Ale",
            "Pacifico Clara",
            "Pagoa Pilsner (Orhi)",
            "Pagoa Red Ale (Gorri)",
            "Pagoa Stout (Zunbeltz)",
            "Pale Ale A.C.T.S.",
            "Pale Ale Centennial",
            "Pale Ale Citra Nugget",
            "Pale Ale Mosaic",
            "Pale Ale Nelson Sauvin",
            "Pale Ale Nelson Sauvin/Summit",
            "Paljas IPA",
            "Palm Spéciale",
            "Pampille",
            "Pannepeut",
            "Pannepot",
            "Pannepot Grand Reserva",
            "Papegaei",
            "Paradox Isle of Arran",
            "Paradox Jura",
            "Paradox Port Dundas",
            "Paradox Springbank",
            "Parisis Ambrée",
            "Parisis Blanche",
            "Parisis Blonde",
            "Parisis Triple",
            "Parpalhon Blanche Estivale",
            "Parpalhon Blonde",
            "Partizan Brewing Stout",
            "Pas Comme d'Hab - faible houblonnage (la)",
            "Pas Comme d'Hab - fort houblonnage (la)",
            "Past Masters Old Burton Extra",
            "Pater Lieven Triple",
            "Paulaner Hefe-Weissbier",
            "Pavoa",
            "Paysanne Blonde (la) (été 2010)",
            "Pêche Mel Bush",
            "Pêché Mortel",
            "Pêcheresse (la)",
            "Pelforth Ambrée",
            "Pelforth Brune",
            "Penhors Ambrée",
            "Penhors Stout",
            "Père Noël",
            "Perle Hop Cascade",
            "Perlenbacher Premium Pils",
            "Peroni Nastro Azzuro",
            "Perpetual IPA",
            "Pesée (la)",
            "Pétasse (la)",
            "Peter, Pale and Mary (sans gluten)",
            "Petite Princesse (la)",
            "Petrus Aged Pale",
            "Petrus Gouden Tripel",
            "Petrus Oud Bruin",
            "Phi",
            "Philomenn Rousse",
            "Philomenn Stout",
            "Philomenn Tourbée",
            "Pictalie Ambrée",
            "Pictalie Blanche",
            "Pictalie Blonde",
            "Pictave (la)",
            "PiedBoeuf Blonde",
            "PiedBoeuf Foncé",
            "PiedBoeuf Triple",
            "Pierre de Lune",
            "Pietra",
            "Pigeonoël",
            "Pilloise Ambrée (la)",
            "Pilloise Brune (la)",
            "Pils des 3 Canaux",
            "Pilsner Urquell",
            "Pin-Up Blanche",
            "Pin-Up Blonde",
            "Pin-Up Rousse",
            "Pineau des Charentes Lambic",
            "Pinkus Classic",
            "Pipedream",
            "Piper's Gold",
            "Piraat",
            "Piro Blonde",
            "Piro Bruin",
            "Piste Noire",
            "Pit Caribou IPA Américaine",
            "Pleine Lune Bière d'Hiver",
            "Pliny The Elder",
            "Podge Belgian Stout",
            "Podge Bourgogne Oak Aged",
            "Poivrotte (la)",
            "Polar",
            "Pony Stout",
            "Postel Double",
            "Postel Triple",
            "Postman Knock's",
            "Pousset",
            "Pousset Ambrée",
            "Pousset Pomme",
            "Prairial",
            "Primator 24",
            "Prime (la)",
            "Primus",
            "Procrastinator",
            "Promised to the Night",
            "Prototype",
            "Prunus",
            "PsaïkoDéclik",
            "Psychedelia",
            "Punk IPA",
            "Que Dansent les Nymphes",
            "Queen of Langstross",
            "Quercorb Bière de Mars",
            "Queue de Charrue Ambrée",
            "Queue de Charrue Blonde",
            "Queue de Charrue Brune",
            "Queue de Charrue Triple",
            "Quilmes",
            "Quintine Ambrée",
            "Quintine Blonde",
            "Quinto",
            "Raftman",
            "Raging Bitch",
            "Ragnagnarök",
            "Raid Biere",
            "Railway Porter",
            "Rainette Ambrée",
            "Rainette Bitter",
            "Rainette Blanche",
            "Rainette de Noël",
            "Rainette Fumée",
            "Rainette Noire",
            "Rainette Rouge",
            "Rainette Space",
            "Ramberte (la)",
            "Rambling Skunk (the)",
            "Ramée Blond",
            "Randalls Mild",
            "Randalls Premium Bitter",
            "Rasputin",
            "Ratz Ambrée",
            "Ratz Ambrée Bio",
            "Ratz Blanche",
            "Ratz Blanche Bio",
            "Ratz Blonde",
            "Ratz Blonde Bio",
            "Ratz Brune",
            "Re Ale",
            "Red Alert",
            "Red Fox IPA",
            "Red Hooter",
            "Red Kite Ale",
            "Red Poppy Ale",
            "Rédor Pils",
            "Reflet de France",
            "Reinaert Grand Cru",
            "Reservoir Hops",
            "Revdo Céanie",
            "Rêve d’Etoiles",
            "Rhub'I.P.A.",
            "Ribella",
            "Ribouldingue Amarillo",
            "Ribouldingue Naturelle",
            "Ricochet",
            "Rigor Mortis",
            "Rince Cochon (le)",
            "Rio Reserva",
            "Rioule (la)",
            "Rip Tide",
            "Rivière d'Ain Ambrée",
            "Rivière d'Ain Blonde",
            "Road Dog Porter",
            "Robust Porter",
            "Roche Noire",
            "Rochefort 10",
            "Rochefort 6",
            "Rochefort 8",
            "Rodenbach",
            "Rodenbach Grand Cru",
            "Rodenbach Vin de Céréales 2004",
            "Rodenbach Vintage 2007",
            "Rombière Noire",
            "Ron and the Beast Ryan",
            "Rooie Dop Chica Americana IPA",
            "Rosé de Gambrinius",
            "Rosée d'Hibiscus",
            "Rosko Ambrée",
            "Rosko Stout",
            "Rote Zora",
            "Rouge Flamande (la)",
            "Rouquine (la)",
            "Rousse du Vaudrée (la)",
            "Rousse Pète",
            "Route des Epices",
            "Royal Brown",
            "Rubus",
            "Ruination IPA",
            "Rulles Blonde",
            "Rulles Brune",
            "Rulles Cuvée Meilleurs Voeux (la)",
            "Rulles Estivale",
            "Rulles Triple",
            "Rumble",
            "Rye PA",
            "Rye-PA",
            "SA Gold",
            "Sabot",
            "Sabot Bière de Fête",
            "Sabot Chili Chocolat",
            "Sabot de Vénus",
            "Sabot Vieux Chêne",
            "Sabot-Danse",
            "Sabotage",
            "Safari Lager",
            "Sagres",
            "Saint Amatus 12",
            "Saint Côme",
            "Saint Georges (la)",
            "Saint Lamvinus",
            "Saint Monon au Miel (la)",
            "Saint Monon Spéciale Noël (la)",
            "Saint Patrick",
            "Saint Petersburg Imperial Russian Stout",
            "Saint Petersburg Speyside Whisky Reserve",
            "Saint Pierre Noël Tradition (la)",
            "Sainte Colombe Bière d'Hiver",
            "Saison 1858",
            "Saison 1900",
            "Saison d'épeautre",
            "Saison de Dottignies",
            "Saison des Amours",
            "Saison du Meyboom",
            "Saison Dupont",
            "Saison Dupont Dry Hopping",
            "Saison D’Erpe-Mere",
            "Saison Regal",
            "Saison Sauvin",
            "Saison XIII",
            "Sakura",
            "Salamandre (la)",
            "Salève Amiral Benson",
            "Salève Barley Wine",
            "Salève Blanche",
            "Salève Blonde",
            "Salève India Pale Ale",
            "Salève Mademoiselle IPA",
            "Salève Mozaic Black Bitter",
            "Salève Nouveaux Mondes",
            "Salève Oyster Stout",
            "Salève Sorachi Ace Bitter",
            "Salève Special Bitter",
            "Salève Stout",
            "Salève Stout Framboise",
            "Salève Tourbée",
            "Salève Twin Bitter",
            "Salève Weizen",
            "Salitos Tequila",
            "Salvator",
            "Salzspeicher Sour Porter Cherry",
            "Samichlaus",
            "Samuel Adams American Kriek",
            "San Miguel",
            "Sancerroise Val d'Or Rousse (la)",
            "Sancerroise à Lentille Verte du Berry",
            "Sancerroise au Gruyt",
            "Sanctification",
            "Sans Dessus Dessous",
            "Sant Erwann",
            "Sant Gwenole",
            "Sant Patern",
            "Saphir Bock",
            "Sapporo",
            "Sara Brune",
            "Satinée (la)",
            "Schieve Tabarnak",
            "Schneider Weisse Original",
            "Schneider Weisse Tap 5 Hopfen-Weisse",
            "Schubart-Dunkel",
            "Schwaben Bräu Weihnachtsbier",
            "Schwortz (la)",
            "Schönramer Imperial Stout",
            "Science Infuse Triple",
            "Scotch Silly",
            "Sculpin IPA",
            "Seasoned Veteran",
            "Seigle #2",
            "Sequoia",
            "Serena",
            "Série Noire",
            "Servais",
            "Seven Giraffes",
            "Shakespeare Oatmeal Stout",
            "Shepherd Neame 1698-1998",
            "Shoals Pale Ale",
            "Shoreditch Triangle IPA",
            "Sierra Nevada Pale Ale",
            "Sierra Nevada Porter",
            "Sierra Nevada Stout",
            "Signature Cyril Fonchy (batch #1)",
            "Signature Olivier Duthoit (batch #2)",
            "Silly Saison",
            "Simcoe Lager",
            "Singha Premium Import Lager",
            "Skol Pils",
            "Sladek Hopburst",
            "Slagmuylder Kerstbier-Noël",
            "Smithwick's",
            "Smoked Porter",
            "Smoked Rye IPA",
            "Smugglers Stout",
            "Smuttynose IPA",
            "Smuttynose Robust Porter",
            "Snake Dog IPA",
            "Sneck Lifter",
            "Soft Bobby",
            "Soizic",
            "Solstice d'Été aux Framboises",
            "Solstice d'Hiver",
            "Songe-Fête Ambrée",
            "Sorachi Ace Ginger Saison",
            "Sorachi Ace Single Hop IPA",
            "Sorcière du Berry Ambrée (la)",
            "Sorcière du Berry Bière Blonde (la)",
            "Sorcière du Berry Blanche (la)",
            "Soundwave IPA",
            "Sour Brown",
            "Sous les Pavés",
            "Soyeuse Ambrée (la)",
            "Soyeuse Ambrée Saison Framboise (la)",
            "Soyeuse Blonde (la)",
            "Soyeuse Blonde Saison Miel (la)",
            "Soyeuse Rousse (la)",
            "SPA",
            "Space Frontier",
            "Spécial Block 6",
            "Special Extra Export Stout",
            "Speed King",
            "Speedway Stout",
            "Speltor Bière Bio",
            "Spendrups Export Premium Lager",
            "Spezial Rauchbier Lager",
            "Spike and Jerôme's",
            "Spitfire",
            "Spoum Triple",
            "Squale Harmonique (le)",
            "St Andrews Ale",
            "St Bernardus Abt 12",
            "St Bernardus Blanche",
            "St Bernardus Christmas Ale",
            "St Bernardus Pater 6",
            "St Bernardus Prior 8",
            "St Bernardus Triple",
            "St Edmunds",
            "St Erhard",
            "St Feuillien Blonde",
            "St Feuillien Brune",
            "St Feuillien Cuvée de Noël",
            "St Feuillien Triple",
            "St Glinglin Ambrée",
            "St Glinglin Houblon",
            "St Glinglin Noël",
            "St Glinglin Triple",
            "St Idelsbald Blonde",
            "St Julien (la)",
            "St Louis Glühbier",
            "St Peter's Ruby Red Ale",
            "St Rieul Noël",
            "St Stefanus Blond",
            "St. Georges Blonde",
            "Steiger Gold",
            "Stella Artois",
            "Stelle & Strisce",
            "Stille Nacht",
            "Stone IPA",
            "Stone Pale Ale",
            "Stone Smoked Porter",
            "Stout 8",
            "Stout Leroy",
            "Stout Rullquin",
            "Stout'Voiles Dehors",
            "Stouterik",
            "Straff",
            "Strawberry Boby",
            "Street Porter",
            "Strong Suffolk Ale",
            "Stronggus",
            "Struise Rosse",
            "Struise Witte",
            "Stuttgarter Hofbräu Pilsner",
            "Stuttgarter Hofbräu WeihnachtsBier",
            "Störtebeker Schwarzbier",
            "Summer Swallow",
            "Summit Single Hop IPA",
            "Super 64",
            "Super Bock",
            "Super des Fagnes Blonde",
            "Super des Fagnes Brune",
            "Super Nova Dunkel Weizen",
            "Super Nova Triple",
            "Super Power",
            "Supplication",
            "Sur Mosaic",
            "SVEA IPA",
            "Sylvanecte",
            "Sylvie Cious (la)",
            "Système D Ambrée",
            "Système D Blonde",
            "Système D Brune",
            "T.S.O. lotto 15",
            "Tabachéra",
            "Tannen Zäpfle",
            "Tantad",
            "Taras Boulba",
            "Taras Runa",
            "Tarraco Amber",
            "Tarraco IPA",
            "Tartarin's Top Tipple",
            "Tasty",
            "Tatou",
            "Tchanquée (la)",
            "Teckel Bull",
            "Telenn Du",
            "Tempelier",
            "Tempête du Désert",
            "Terre 2010",
            "Terrible",
            "Tête au Carré",
            "Tête de Mule Blonde",
            "Tête Rousse",
            "Teusser",
            "Texas Ranger Barrel Aged",
            "Texas Ranger Vanilla and Cocoa Beans Barrel Aged",
            "The Crow",
            "The Kimmie, the Yink and the Holy Gose Ale",
            "The Maharaja IPA",
            "The Oracle",
            "The Poker Series - Roi de Coeur",
            "This. Is. Lager",
            "Thomas Becket Ambrée de Bourgogne",
            "Thomas Becket Brune de Bourgogne",
            "Thomas Hardy's Ale",
            "Thou Blanche",
            "Thurn und Taxis Dunkle Weisse",
            "Thurn und Taxis Kristall Weizen",
            "Thurn und Taxis Weissbier",
            "Til... Fra... Via Mikkeller",
            "Timmermans Faro",
            "Timmermans Gueuze",
            "Tire Bite Golden Ale",
            "Titan IPA",
            "Titje",
            "Tokyo*",
            "Tongerlo Blond",
            "Tongerlo Double Brune",
            "Too Much Coffee Man",
            "Torchebugne Blondinette",
            "Torpille (la)",
            "Torra Ambrata",
            "Torra Blonda",
            "Tourangelle (la)",
            "Tournay",
            "Tournay Blonde",
            "Tournay Noire",
            "Tournemine Real Ale",
            "Toutoblack (la)",
            "Traboule",
            "Trappe Blond (la)",
            "Trappe Dubbel (la)",
            "Trappe Puur (la)",
            "Trappe Quadrupel (la)",
            "Trappe Quadrupel Oak Aged (la)",
            "Trappe Tripel (la)",
            "Traquair House Ale",
            "Traquair Jacobite Ale",
            "Trashy Blond",
            "Tri Martolod Blanche",
            "Tri Martolod Blonde",
            "Tri Martolod Brune",
            "Tri Martolod Rousse",
            "Tricerat'Hops",
            "Tripel de Lente Sauternes",
            "Tripel Karmeliet",
            "Triple Hop Bock",
            "Triple Hot - Saison des Ardeurs",
            "Triple Moine",
            "Trobairitz Saison",
            "Trois Epis Bière de Noël",
            "Trois Monts",
            "Trois Pistoles",
            "Trollebier Blond",
            "Trop’ (la)",
            "Troubadour Magma",
            "Troubadour Obscura",
            "Troubadour Westkust",
            "Troubadoure (la)",
            "True Rebel",
            "Tsarina Esra Reserva",
            "Tsingtao Biere",
            "Tsingtao Dark",
            "Tsjeeses",
            "Twin Peaks",
            "Twisted Thistle IPA",
            "Two Gypsies Our Side",
            "Tzarine Imperial Stout 13",
            "Tzarine Imperial Stout 9",
            "Uberach Bière Ambrée",
            "Uberach Bière Blonde",
            "Uerige Doppelsticke",
            "Uerige Sticke",
            "Uggi Brew #9",
            "Un*Earthly",
            "Unicron",
            "Union",
            "Universelle (l')",
            "Unleash the Yeast American Ale",
            "Unleash the Yeast Bavarian Weizen",
            "Unleash the Yeast Belgian Trappist",
            "Unleash the Yeast Pilsen Lager",
            "Ur Bock Dunkel",
            "Urbock",
            "Ursulines Ambrée (les)",
            "Ursulines Blanche",
            "Ursulines Blonde (les)",
            "Ursulines Dorée (les)",
            "Urthel Hibernus Quentum",
            "Urthel Hop It",
            "Urthel Parlus Magnificum",
            "Urthel Saisonnière",
            "Urthel Samaranth",
            "V Cense",
            "Vache à Bière Blanche",
            "Vache à Bière Blonde",
            "Vache à Bière Brune",
            "Vache à bière de Noël (la)",
            "Vache à Bière Indian Pale Ale",
            "Vache à Bière Pale Ale",
            "Vache Folle Imperial Milk Stout (la)",
            "Vache Folle Milk Stout",
            "Vaillant Fourquet Blanche",
            "Valeir Extra",
            "Vampire Slayer",
            "Vapeur Cochonne",
            "Vaudrée Blonde (la)",
            "Vaudrée Brune (la)",
            "Vedett Extra Ordinary IPA",
            "Vent d'Ange",
            "Verboten",
            "Verdi Imperial Stout",
            "Vermontoise (la)",
            "Véronique Lucienne",
            "Verzet Oud Bruin",
            "Veuve Noire (la)",
            "Vicaris Tripel/Gueuze",
            "Vichtenaar",
            "Vieux Bruges blanche",
            "Vieux Temps",
            "Vildmoseøl",
            "Villers Triple",
            "Villers Vieille",
            "Vintage Ale",
            "Violent Shared",
            "Vision Dyonisiaque",
            "Vital Spark",
            "Vivat",
            "Vivat Triple",
            "Viven Imperial IPA",
            "Viven Porter",
            "Volcelest Blonde",
            "Voll Damm Doble Malta",
            "Volpina",
            "Vondel",
            "Vue sur l'Amer",
            "Wadesda #4",
            "Warsteiner",
            "Waterloo Rossa",
            "Watneys Scotch Ale",
            "Watou Tripel",
            "Watou's Wit",
            "Weihenstephaner Hefe-Weissbier",
            "Weihenstephaner Hefe-Weissbier Dunkel",
            "Weihenstephaner Kristallweissbier",
            "Weltfreude",
            "Westmalle Double",
            "Westmalle Triple",
            "Westoek XX",
            "Westvleteren 12",
            "Westvleteren 6 Blond",
            "Westvleteren 8",
            "What the Fuck - Palisade Sorachi Ace",
            "Whistable Bay",
            "White Shield",
            "Whyld Mild",
            "Wild Boar",
            "Wild Swan",
            "Wildbeest",
            "Wilfort",
            "Williams Red",
            "Wilson Stout",
            "Winterkoninck",
            "Winterscotch",
            "Witkap Pater Dubbel",
            "Witkap Pater Stimulo",
            "Witkap Pater Tripel",
            "Witte Trappiste",
            "Wollt Ihr das Bett in Flammen Sehen",
            "Worthington's",
            "Wychcraft",
            "X-Mas Zinnebir",
            "Xan Hefe Weissbier",
            "XI.I",
            "XIV",
            "XO Biere",
            "XX Bitter",
            "XXX Bitter",
            "XXXX Quadruple",
            "Xyauyu Barrel 2010",
            "Yan Jing Biere",
            "Ye Olde Merry Nighting'Ale",
            "Yéti",
            "Yote (la)",
            "Youn (la)",
            "Young's Double Chocolate",
            "Ypres Reserva",
            "Zatte Bie",
            "Zeezuiper",
            "Zeitgest",
            "Zero Gravity",
            "Zinnebir",
            "Zithum Ambrée",
            "Zona Cesarini",
            "Zumbi",
            "Zwanze 2014 (Cuvée Florian)",
            "Zwart & Wit",
            "Zwart Bloed",
            "Zwet.be",
            "Zywiec Porter",
            "ZZ+",
            "Zzzisch",
        ]

        self.offre_biere_msg = sender.nick + " offre une " + random.choice(self.biere_list) + " à " + msg[4:] + ": cul sec beau mec !!!"
        self.c.privmsg(target, self.offre_biere_msg)
